### ISSUE TITLE
部分插件配置生成错误#410 terra

### ISSUE THREAD

**Issue by lthuas** [BlocklyNukkit/PowerNukkitX#104]
# 🐞 插件兼容性问题汇报

👉 我在使用 [git-22d6adf](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1869855432) terra版本的pnx核心当中，首次加载一些插件，插件配置里会生成一个非插件该有配置内容的配置，导致插件报错无法启用
这个错误配置的图床
![error log 1](https://seikim.com/i/2022/02/25/ppuww5.png)
开服签到插件报错的图床
![error log 2](https://5fou.com/i/2022/02/25/prqr55.png)
这里拿了 [签到插件](https://www.minebbs.com/resources/signin.3129/) 进行的测试

### ▶ 复现步骤

使用 [git-22d6adf](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1869855432) terra版本的pnx核心加载签到插件
开启服务器，即可出现签到插件报错并且关闭了插件，签到插件第一次生成的配置内容也非插件本身该有的配置内容
插件应该有的配置
![plugin right cofing image](https://seikim.com/i/2022/02/25/qgqmai.png)
实际上的错误配置
![This is an image](https://seikim.com/i/2022/02/25/ppuww5.png)

### ✍ 其它
在另外一个服务器测试了 [git-b407892](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1870714368)master的pnx，可以正常生成插件配置内容，无报错
于是我把 [git-b407892](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1870714368)master的pnx生成的插件配置复制到 [git-22d6adf](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1869855432) terra的对应插件配置里进行覆盖，在启用这个terra pnx服，于是可以正常启用
所以我发现是 [git-22d6adf](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1869855432) terra pnx核心的问题

**Comment by lthuas** [comment]
格式好像乱了，图床也没了，我稍后在发一个

**Comment by lthuas** [comment]
我感觉会有大批插件的config.yml出现问题，我只发现这一个插件的原因是，原有配置是使用412master核心生成的，其他插件也是在这个时候生成出来的，后面我换了410terra版的核心，期间删掉了这个原有配置，所以就重新生成了一个，发现了这个核心生成配置会导致错误的问题

**Comment by Superice666** [comment]
由 #87775ebcff09bfce1b7fa4ca0f506cb509be5fe3 修复
