### ISSUE TITLE
藤蔓错误生成

### ISSUE THREAD

**Issue by lt-name** [BlocklyNukkit/PowerNukkitX#11]
# 🐞 错误汇报

### 📸 截图或视频
![image](https://user-images.githubusercontent.com/45508179/152529420-0ac91973-3ae2-4da4-9f5a-5feea7636c8f.png)

**Comment by Superice666** [comment]
需要进一步检查BlockFace相关逻辑是否正确

**Comment by Superice666** [comment]
请问能提供截图种子和坐标吗，便于测试，感谢。

**Comment by lt-name** [comment]
我也没存。。。。只能重新找了
