### ISSUE TITLE
Bug with the glowing frame

### ISSUE THREAD

**Issue by MEFRREEX** [BlocklyNukkit/PowerNukkitX#114]
# 🐞 错误汇报
👉 尽可能详实地描述错误信息
While I was testing the terra branch, I found a funny flaw. 
When you put a glowing frame and put the glowing frame itself into that frame or a normal frame, a fox call egg appears there instead of the frame, this only works with the glowing frame. This flaw is present in both branches.

📸 截图或视频
https://user-images.githubusercontent.com/83061703/155905963-cbf43dcc-1160-439c-8d9b-ff0a3761d1df.mp4

**Comment by Superice666** [comment]
fixed by #118
