### ISSUE TITLE
发光展示框复制后是普通展示框

### ISSUE THREAD

**Issue by CivicXFB** [BlocklyNukkit/PowerNukkitX#116]
# 🐞 错误汇报

### ▶ 复现步骤

将发光展示框放在墙上或地下点击鼠标复制他会给普通展示框

### ✔ 预期行为

会给发光展示框

### ❌ 实际行为

给了普通展示框

### 💬 其他信息

主分支PNX#107

**Comment by smartcmd** [comment]
> 

你是完全不用上学的吗:(

**Comment by CivicXFB** [comment]
在实训摸鱼呢

**Comment by smartcmd** [comment]
> 在实训摸鱼呢

离谱

**Comment by CivicXFB** [comment]
![屏幕截图 2022-03-01 112103](https://user-images.githubusercontent.com/61540722/156098813-8da1bd9b-391f-4e00-96c2-e0fa7ee9b0ed.png)
![屏幕截图 2022-03-01 112122](https://user-images.githubusercontent.com/61540722/156098818-51a555fd-6f3e-42c9-b267-5434bc702c91.png)

**Comment by CivicXFB** [comment]
上面是证据

**Comment by CoolLoong** [comment]
Fixed #118
