### ISSUE TITLE
PNX新发现的BUG

### ISSUE THREAD

**Issue by chencu5958** [BlocklyNukkit/PowerNukkitX#119]
# 🐞 错误汇报

1. 蛋糕无法使用，怀疑是PN时期的BUG
2. 铁匠台无法使用
3. 三叉戟会莫名着火
4. 以及不可点燃方块可以用打火石点燃

### 💬 其他信息

测试用的[版本](https://github.com/BlocklyNukkit/PowerNukkitX/actions/runs/1903349641)

**Comment by chencu5958** [comment]
相关图片视频
![XIKR A7SY2E)Y 8 H9W(`99](https://user-images.githubusercontent.com/82279230/156782444-8dc8b606-5d9d-42e1-b61a-5e22b2f7bf5d.png)

https://user-images.githubusercontent.com/82279230/156782450-3d0c5f37-0970-48e3-89f2-3af07eded7fd.mp4

这些内容由discord群中的群友提供，蛋糕的BUG为我本人发现，其余的则为DC群里的群友发现的

**Comment by Superice666** [comment]
格式错误
