### ISSUE TITLE
不可点燃方块可以用打火石点燃

### ISSUE THREAD

**Issue by Superice666** [BlocklyNukkit/PowerNukkitX#123]
# 🐞 错误汇报

不可点燃方块可以用打火石点燃 @chencu5958 

### 📸 截图或视频

https://user-images.githubusercontent.com/82279230/156782450-3d0c5f37-0970-48e3-89f2-3af07eded7fd.mp4

### 💬 其他信息

build #434

**Comment by lt-name** [comment]
无法复现
（疑似被 smartcmd 修复，未知提交）
