### ISSUE TITLE
站在仙人掌上没有伤害

### ISSUE THREAD

**Issue by CivicXFB** [BlocklyNukkit/PowerNukkitX#124]
# 🐞 错误汇报

我发现在pnx上 玩家站在仙人掌上是没伤害的

### ▶ 复现步骤

找到沙漠地形或者放置仙人掌
站在仙人掌方块上

### ✔ 预期行为

有伤害

### ❌ 实际行为

无伤害

### 📋 Debug information

无

### 💢 错误堆栈或崩溃日志

无

### 💬 其他信息

主分支PNX#107

**Comment by Mcayear** [comment]
仙人掌伤害频率过快。

https://user-images.githubusercontent.com/48203962/156912569-ee209a3a-25ac-474a-b975-9c4129db7cc1.mp4
