### ISSUE TITLE
LevelProvider新加的关于获取维度的方法在多线程环境下有几率导致空指针异常

### ISSUE THREAD

**Issue by smartcmd** [BlocklyNukkit/PowerNukkitX#135]
![image](https://user-images.githubusercontent.com/60499296/156892919-2e544a93-be54-4c63-b0ad-35f8086473d0.png)
![image](https://user-images.githubusercontent.com/60499296/156892944-7981446f-4a62-4721-95cc-2ee38130adad.png)

**Comment by Superice666** [comment]
fixed by #137

**Comment by PocketMiner92** [comment]
Anvil Format 🤣
