### ISSUE TITLE
滴水石锥无法填充炼药锅

### ISSUE THREAD

**Issue by Superice666** [BlocklyNukkit/PowerNukkitX#136]
# 🐞 错误汇报

尚未实现滴水石锥填充炼药锅功能。

### ✔ 预期行为

当滴水石锥下方为炼药锅，上方一格的方块上为水或岩浆时，炼药锅将被逐渐填满。

### ❌ 实际行为

Null

**Comment by smartcmd** [comment]
火速给你写了
