### ISSUE TITLE
玩家站在船上会掉入水中

### ISSUE THREAD

**Issue by CoolLoong** [BlocklyNukkit/PowerNukkitX#143]
# 🐞 错误汇报

当玩家站在船上时过一会会掉下来进入水中
### ▶ 复现步骤

打开游戏，找到河流，放船，站在上面

### ✔ 预期行为

人物站在船上

### ❌ 实际行为

掉入水中

**Comment by chencu5958** [comment]
这个应该是正常现象，基岩版和java版在原版特性等方面存在一些比较明显的差距

**Comment by smartcmd** [comment]
如果是特性的话我就先关了
