### ISSUE TITLE
探测铁轨无法激活使用激活铁轨

### ISSUE THREAD

**Issue by chencu5958** [BlocklyNukkit/PowerNukkitX#145]
# 🐞 错误汇报

如标题所示
### 📸 截图或视频

使用Git-65cd5cb构建版本

**Comment by chencu5958** [comment]
同时激活铁轨还存在激活范围问题，使用拉杆等强制激活时只会激活周围的单个激活铁轨，在原版中是一整条都被激活

**Comment by chencu5958** [comment]
高速铁轨可能也无法被探测铁轨激活，但使用红石拉杆等强制激活范围是正常的

**Comment by smartcmd** [comment]
修了,顺便修了几个你没发现的
