### ISSUE TITLE
加载区块时有概率导致客户端崩溃

### ISSUE THREAD

**Issue by smartcmd** [BlocklyNukkit/PowerNukkitX#21]
# 🐞 错误汇报
如题，并且再次进入时还会崩溃

### 📸 截图或视频

![01 UIIWP(GI7P6OM5T0GOQX](https://user-images.githubusercontent.com/60499296/152780553-3cd57893-9fbe-4558-ac3f-c5706044a8ed.png)
下面是橡木林    种子：1643969748183

![7T)OV V15J0ZL$4W0IIQOWY](https://user-images.githubusercontent.com/60499296/152780598-561d1a0b-d2d2-4dee-a554-26290cee57f3.png)
(world, -193.1253, 88.8593, -1825.9677)
种子：1644231384637

### ▶ 复现步骤
跑图，然后等待bug出现

### ✔ 预期行为
区块正常加载，没有标题情况出现

### ❌ 实际行为
如标题

### 💢 错误堆栈或崩溃日志
服务端无报错

### 💬 其他信息
也许是生物群系出问题了。。。？

**Comment by Superice666** [comment]
很可能已经被 #18 修复，需要更多测试

**Comment by Superice666** [comment]
暂时关闭，如果bug复现则重新开放。
