### ISSUE TITLE
[384 高度] 0以下 256以上的红石元件无法正常工作

### ISSUE THREAD

**Issue by zimzaza4** [BlocklyNukkit/PowerNukkitX#23]
# 🐞 错误汇报

0 ~ 256 层红石元件无法正常工作
红石元件无法被激活

### 📸 截图或视频

![Screenshot_20220207_200255_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/152785532-a9d99325-4553-4f96-aa5d-1752ae78d497.jpg)

### ▶ 复现步骤

去0~256层之外使用红石

### ✔ 预期行为

红石元件应该正常工作

### ❌ 实际行为

红石元件没有正常工作
按钮和拉杆没法互动

### 💢 错误堆栈或崩溃日志

无

**Comment by Superice666** [comment]
由 #87 修复
