### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by CoolLoong** [BlocklyNukkit/PowerNukkitX#25]
# 🐞 错误汇报

java.util.ConcurrentModificationException异常,使用384-world分支980f2da Commit构建，在使用鞘翅快速跑图的过程中提示报错，影响未知。
### 📸 截图或视频

![image](https://user-images.githubusercontent.com/69153398/152789090-70b1d26e-02a5-47d5-9d82-195046f7e72d.png)

### ▶ 复现步骤

未知

### ✔ 预期行为

没有报错

### ❌ 实际行为

服务端提示报错

**Comment by smartcmd** [comment]
这玩意应该是修了，没复现过
