### ISSUE TITLE
末地维度无法进入

### ISSUE THREAD

**Issue by Ootmnt150oO** [BlocklyNukkit/PowerNukkitX#27]
# 🐞 错误汇报

### 📸 截图或视频

![image](https://user-images.githubusercontent.com/60053027/152801264-08f6ad4f-5a4a-40a5-b018-f621c2358190.png)

**Comment by zimzaza4** [comment]
这是384高度世界造成的问题
待解决吧

**Comment by Superice666** [comment]
经测试，下界可以进入
![image](https://user-images.githubusercontent.com/51087818/152908750-04a05464-7ab7-4f5e-8b8e-e0ec7217f65c.png)
