### ISSUE TITLE
使用烟花火箭飞行时烟花bug

### ISSUE THREAD

**Issue by CivicXFB** [BlocklyNukkit/PowerNukkitX#31]
# 🐞 错误汇报

在mc中使用烟花火箭飞行时，烟花转换成跟随飞行的粒子而不在使用方位燃放烟花
与PN对比发现都有相同bug
### 📸 截图或视频

![3N2WYM~4`LT8QP)EP2{G5`R](https://user-images.githubusercontent.com/61540722/152913425-0c8e567c-6099-4673-a682-1978c21f8a37.png)
![ZEVQY 47DLYF``~Z3 SZ I5](https://user-images.githubusercontent.com/61540722/152913426-ef1ea4bf-0f4f-43ad-9fb6-76e4d3238b38.png)

### ▶ 复现步骤

1.打开鞘翅飞行 
2.使用烟花加速（100%触发）

### ✔ 预期行为

烟花轨迹会跟随你的飞行轨迹

### ❌ 实际行为

他在加速的位置燃放而非跟随

### 📋 Debug information

无
### 💢 错误堆栈或崩溃日志

无

### 💬 其他信息

使用 PowerNukkitX #30构建
服务端操作系统 WindowsServer 2016
RAM 2G
CPU E5-2682V4 1core

参照对比

PowerNukkit 1.6-PN-MC1.18.0-B129
服务端操作系统 WindowsServer 2016
RAM 2G
CPU E5-2682V4 1core

**Comment by CivicXFB** [comment]
https://user-images.githubusercontent.com/61540722/152914383-0753378f-13f0-43ef-8e28-d55a3b847635.mp4

**Comment by CivicXFB** [comment]
真跟随

**Comment by CivicXFB** [comment]
有

**Comment by CivicXFB** [comment]
还是有些问题例如烟花在飞行过程中跟随着 原版非跟随状态

**Comment by zimzaza4** [comment]
原本是隐形跟随

**Comment by zimzaza4** [comment]
原版是隐形跟随

**Comment by CoolLoong** [comment]
> 还是有些问题例如烟花在飞行过程中跟随着 原版非跟随状态

原版相当于是烟花粒子跟随

**Comment by zimzaza4** [comment]
> > 还是有些问题例如烟花在飞行过程中跟随着 原版非跟随状态
> 
> 原版相当于是烟花粒子跟随

但是这个烟花真实存在
