### ISSUE TITLE
萤石生成异常

### ISSUE THREAD

**Issue by Hanmo123** [BlocklyNukkit/PowerNukkitX#38]
# 🐞 错误汇报

地狱的萤石生成分散

### 📸 截图或视频

![3`}7UL@448_N8~DWC5V(A62](https://user-images.githubusercontent.com/32361024/152975624-fec698b1-4037-4266-84bb-522cd8315fda.png)

### ▶ 复现步骤

进入地狱即可复现

### ✔ 预期行为

集中分布的萤石

### ❌ 实际行为

![image](https://user-images.githubusercontent.com/32361024/152975717-3cd58ba0-e422-4dc3-8586-9e1d6b4d8887.png)

**Comment by Superice666** [comment]
由 #43 修复
