### ISSUE TITLE
发光墨囊对告示牌的发光效果会失效

### ISSUE THREAD

**Issue by Mcayear** [BlocklyNukkit/PowerNukkitX#55]
# 🐞 错误汇报
当你在一个区块使用发光墨囊点亮告示牌后，传送至较远的看不到该区域的地方点亮另一个告示牌。
再传送回第一个区块，可以发现告示牌的发光效果已经丧失。

两个人看到的发光效果不一致

### 📸 截图或视频
![-6e9832ce337e3954](https://user-images.githubusercontent.com/48203962/153566194-089e1d17-2d9f-4433-b032-243ca01a023f.jpg)

**Comment by lt-name** [comment]
在 https://github.com/BlocklyNukkit/PowerNukkitX/commit/9ac4c7ce83bbe6274ec9daab71e40fa60a4fa7a9 修复
