### ISSUE TITLE
please translate it to english

### ISSUE THREAD

**Issue by PocketMiner92** [BlocklyNukkit/PowerNukkitX#79]
# ❇ Feature Request
 Title say all

**Comment by Superice666** [comment]
We're woking on it. You can now use Google browser's built-in web translation function as a temporary substitute

**Comment by PocketMiner92** [comment]
OK thanks
I there a testserver for PowernukkitX?

**Comment by zimzaza4** [comment]
no yet

> OK thanks I there a testserver for PowernukkitX?

**Comment by zimzaza4** [comment]
> Or is there a Link for Download?

https://github.com/BlocklyNukkit/PowerNukkitX/actions

**Comment by PocketMiner92** [comment]
Thanks
IS this Software ready for use or Not?

**Comment by lt-name** [comment]
There is still a problem with the map conversion, if you don't consider the previous map, it works fine (Google translate)

**Comment by zimzaza4** [comment]
> Thanks IS this Software ready for use or Not?

No yet
There is still a problem with the conversion of the new world format.
and some 384 world height problems.
