### ISSUE TITLE
Most Plugins from Cloudburst are supported? Joke 100%

### ISSUE THREAD

**Issue by PocketMiner92** [BlocklyNukkit/PowerNukkitX#81]
# 🐞 错误汇报
 All Plugins are written in Java 8!!!!!

**Comment by PetteriM1** [comment]
Java is backwards compatible

**Comment by Mcayear** [comment]
I guess you may have encountered some problems and this wiki can help you.
**Issues without error logs may be ignored.**
https://github.com/BlocklyNukkit/PowerNukkitX/wiki/FAQ

**Comment by zimzaza4** [comment]
Most plugins can be supported
no 100%

**Comment by PocketMiner92** [comment]
I have Tested all Plugins from Cloudburst all nothing works.
Unsupported JDK Version.
All Plugins are Coded with JDK 8
This is why many Plugin Devs from Cloudburst have changed Java 11 to 8.

And all Important Plugins are Not Supported because Development Freeze.
Like Plotssquared, Fawe, Dblib and much more.

**Comment by Superice666** [comment]
@PocketMiner92 I have tested the plugins you mentioned. If you add proper `--add-opens` argument when you start pnx, the three plugins can work.
